name: Generate Datas1

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar Snake Animation
        uses: Platane/snk@v3.0.0
        id: snake-gif
        with:
          github_user_name: kassia-ramos
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
